cc_binary(
    name = "name_age",
    srcs = ["name_age.cpp",
            "std_lib_facilities.h"],
)

cc_binary(
    name = "operators",
    srcs = ["operators.cpp",
            "std_lib_facilities.h"],
)
