cc_binary(
    name = "name_age",
    srcs = ["name_age.cpp",],
    deps = ["//:stdlib",],
)

cc_binary(
    name = "operators",
    srcs = ["operators.cpp",],
    deps = ["//:stdlib",],
)

cc_binary(
    name = "repeated_word",
    srcs = ["repeated_word.cpp",],
    deps = ["//:stdlib",],
)

cc_binary(
    name = "unsafe",
    srcs = ["unsafe.cpp",],
    deps = ["//:stdlib",],
)
