cc_binary(
    name = "currency_converter",
    srcs = ["currency_converter.cpp"],
    deps = [
        "//:stdlib",
        "@boost",
        "@com_github_nlohmann_json//:json",
        "@libcurl//:lib",
    ],
)

cc_binary(
    name = "censor",
    srcs = ["censor.cpp"],
)
